# Generated by Django 4.2 on 2023-04-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlogin', '0004_registration_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='class_name',
            new_name='classname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_no',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='father_name',
            new_name='fathername',
        ),
    ]
